development:
  adapter: 'postgresql'
  database: 'bairdconklinmusic'
  pool: 5
  timeout: 5000

test:
  adapter: 'postgresql'
  database: 'bairdconklinmusic_test'
  pool: 5
  timeout: 5000

production:
  adapter: 'postgresql'
  database: 'bairdconklinmusic_test'
  pool: 5
  timeout: 5000
